"""initial migration

Revision ID: eacd88aad719
Revises: 
Create Date: 2025-05-26 16:49:12.650440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eacd88aad719'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('formularios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('nome_completo', sa.String(length=100), nullable=False),
    sa.Column('documento', sa.String(length=20), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('endereco', sa.String(length=200), nullable=False),
    sa.Column('tipo_imovel', sa.String(length=20), nullable=False),
    sa.Column('telhado_livre', sa.Boolean(), nullable=True),
    sa.Column('telhado_sol', sa.Boolean(), nullable=True),
    sa.Column('gasto_mensal', sa.String(length=50), nullable=True),
    sa.Column('tem_contas', sa.Boolean(), nullable=True),
    sa.Column('tipo_voltagem', sa.String(length=20), nullable=True),
    sa.Column('qtd_pessoas', sa.Integer(), nullable=True),
    sa.Column('objetivo_projeto', sa.String(length=50), nullable=True),
    sa.Column('novos_aparelhos', sa.Boolean(), nullable=True),
    sa.Column('tipo_sistema', sa.String(length=20), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.String(length=200), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('arquivos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('formulario_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('nome_arquivo', sa.String(length=100), nullable=False),
    sa.Column('data_upload', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['formulario_id'], ['formularios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('arquivos')
    op.drop_table('usuarios')
    op.drop_table('formularios')
    # ### end Alembic commands ###
